# This file was generated by GoReleaser. DO NOT EDIT.
class Bitflip < Formula
  desc ""
  homepage ""
  version "0.2.0"

  if OS.mac?
    url "https://github.com/aybabtme/bitflip/releases/download/v0.2.0/bitflip_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "72fb3982421015749089d088559b82731a15c25f8e6057fd899d481963c9a64f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aybabtme/bitflip/releases/download/v0.2.0/bitflip_0.2.0_Linux_x86_64.tar.gz"
      sha256 "926b2ffdddd15f7ed660ee8a78fcd46037f0b94395173a63e1080300289602cc"
    end
  end

  def install
    bin.install "bitflip"
  end
end
