# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitflip < Formula
  desc ""
  homepage ""
  version "0.2.1"

  on_macos do
    url "https://github.com/aybabtme/bitflip/releases/download/v0.2.1/bitflip_ 0.2.1_Darwin_x86_64.tar.gz"
    sha256 "a1cbe4c252876b492046025276ad813f7b462d4ec9b844550724dc445b25574a"

    def install
      bin.install "bitflip"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bitflip
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aybabtme/bitflip/releases/download/v0.2.1/bitflip_ 0.2.1_Linux_x86_64.tar.gz"
        sha256 "199956059476feaec38239d36d0679f57f9438070e41e556a08de44dbd0feefd"

        def install
          bin.install "bitflip"
        end
      end
    end
  end
end
