# This file was generated by GoReleaser. DO NOT EDIT.
class Humanlog < Formula
  desc ""
  homepage ""
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aybabtme/humanlog/releases/download/0.3.0/humanlog_0.3.0_darwin_amd64.tar.gz"
    sha256 "d016f05ef5f252d38e211fffa0396486f8528e8b5f8d91dbbea4a7b5ca5ee9da"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aybabtme/humanlog/releases/download/0.3.0/humanlog_0.3.0_linux_amd64.tar.gz"
      sha256 "6cc9af941c90dbf1f797a4d42ed0dac5c71c115fa2df4d3a492b04b3107b32e0"
    end
  end

  def install
    bin.install "humanlog"
  end
end
