# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Humanlog < Formula
  desc ""
  homepage ""
  version "0.5.0"

  if OS.mac?
    url "https://github.com/aybabtme/humanlog/releases/download/0.5.0/humanlog_0.5.0_darwin_amd64.tar.gz"
    sha256 "37f047366059bd073c1f1a7640e9957f5f0c253c266d67f71f2ce30116a5683e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aybabtme/humanlog/releases/download/0.5.0/humanlog_0.5.0_linux_amd64.tar.gz"
    sha256 "fc68c9ea3f5c0dca2b4c869be01900c249bef68400a194bf8f1a9dee733b49e7"
  end

  def install
    bin.install "humanlog"
  end
end
