# This file was generated by GoReleaser. DO NOT EDIT.
class Humanlog < Formula
  desc ""
  homepage ""
  version "0.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aybabtme/humanlog/releases/download/0.4.2/humanlog_0.4.2_darwin_amd64.tar.gz"
    sha256 "8c95683957b394b40b7d2a1dc7d188a2697913e72c815597e0f696c3f952db93"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aybabtme/humanlog/releases/download/0.4.2/humanlog_0.4.2_linux_amd64.tar.gz"
      sha256 "d2b9a9ab5b3cc06489cb0a38f66290383b9216896ffef531dd89c9b9e6160baf"
    end
  end

  def install
    bin.install "humanlog"
  end
end
