# This file was generated by GoReleaser. DO NOT EDIT.
class Temple < Formula
  desc ""
  homepage ""
  version "0.2.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aybabtme/temple/releases/download/v0.2.4/temple_0.2.4_Darwin_x86_64.tar.gz"
    sha256 "821fdd39b79b84f586bdedc42d59cd8abb14572a95a632608de636d422299bf2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aybabtme/temple/releases/download/v0.2.4/temple_0.2.4_Linux_x86_64.tar.gz"
      sha256 "68c4536901dbbf9af0ae7213b5aa8b8caf5cb841a80aa498372673977268f661"
    end
  end

  def install
    bin.install "temple"
  end
end
