# This file was generated by GoReleaser. DO NOT EDIT.
class Temple < Formula
  desc ""
  homepage ""
  version "0.2.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aybabtme/temple/releases/download/v0.2.3/temple_0.2.3_Darwin_x86_64.tar.gz"
    sha256 "0d116f771d5dff00c3c3f8bbe46ef199bd4f95abce576c3120ca139dec15540f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aybabtme/temple/releases/download/v0.2.3/temple_0.2.3_Linux_x86_64.tar.gz"
      sha256 "5e79ddbf7622369e976f788a1753bfd99a5e440e68a7ab866c2469b8fed7642b"
    end
  end

  def install
    bin.install "temple"
  end
end
